### ISSUE TITLE
come up with idea (5 minute elevator pitch)

### ISSUE THREAD

**Issue by arjun-krishna1** [arjun-krishna1/santatron#1]
fun to make
cool, innovative

**Comment by arjun-krishna1** [comment]
secret santa

**Comment by arjun-krishna1** [comment]
mega santa, everyone pitches keywords, pools money, gets a prize for a single person

**Comment by Joe-Joe-Joe-Joe** [comment]
ML model takes keywords from contributors
- combines 
smart contract takes payment from contributors
- forces trust, low overhead (no pooling money in bank accounts, dealing with paypal etc)

**Comment by arjun-krishna1** [comment]
# santa-tron
## motivation
- coming up with what to buy for friends and family is difficult
- especially when you are a student and you have a low budget

## idea
- santa-tron is a web application
- people pool funds (using cryptocurrency)
- they also pool together ideas
- santa-tron uses this money and ideas
- and a machine learning model to choose a gift, and buy it
