### ISSUE TITLE
Define MVP

### ISSUE THREAD

**Issue by arjun-krishna1** [arjun-krishna1/santatron#2]
# MVP 🧱 
## List of all the gift pools
  - a single page with a list of all of the current gift pools 
  - shows person's name who pool is for
  - button to join gift pool
  - button to close gift pool
## Form to join a gift pool
  - person's name
  - add how much you are contributing to the gift pool
  - add 3 key-words 
## Page to summarize gift pool result after it is done
  - show what the search query phrase was
  - link to the item page that the pool owner should buy
  - show what the pool owner buys for the person
  -  some way for pool owner and contributers to organize getting
  - link to the order page? 
  
# Sprinkles ✨ 
## Smart Contract automatically collects money (maybe buys automatically too)
-  contributor give crypto to gift pool when they join
    - automatically buys gift for person, no need for trusting gift pool owner
## How to contact contributors to send money after? Twilio?

**Comment by arjun-krishna1** [comment]
open site, create gift pool, invite people to it

**Comment by Joe-Joe-Joe-Joe** [comment]
train model using amazon products and keywords that they have already associated (use existing amazon api if possible)
possibly use a google cloud api to use keywords to generate search query phrase?

**Comment by arjun-krishna1** [comment]
have a bunch of circles forming a complicated venn diagram (keywords submitted by users)
finding the region  that overlaps with most of those circles
this is the search query phrase

**Comment by arjun-krishna1** [comment]
MVP defined
